baseURL = '/'
languageCode = 'ja-jp'
title = 'WebLogicドメイン作成手順書'
relativeURLs = true
theme = "hugo-theme-learn"
uglyurls = true
pluralizeListTitles = false # セクションの複数形を防ぐ

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "blue"